using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Plugin.Maui.LocalStore.SourceGenerators;

[Generator]
public sealed class StoreDaoGenerator : IIncrementalGenerator
{
    const string DaoAttribute = "Plugin.Maui.LocalStore.StoreDaoAttribute";
    const string RawAttribute = "Plugin.Maui.LocalStore.StoreRawAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var daos = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DaoAttribute,
                static (node, _) => node is InterfaceDeclarationSyntax,
                static (ctx, _) => Describe(ctx))
            .Where(static dao => dao is not null);

        context.RegisterSourceOutput(daos, static (spc, dao) =>
        {
            if (dao is { } model)
            {
                spc.AddSource(model.HintName, SourceText.From(model.Source, Encoding.UTF8));
            }
        });
    }

    static DaoModel? Describe(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol iface || iface.TypeKind != TypeKind.Interface)
        {
            return null;
        }

        var attribute = context.Attributes[0];
        var collection = attribute.ConstructorArguments.Length > 0
            ? attribute.ConstructorArguments[0].Value as string
            : null;
        if (string.IsNullOrWhiteSpace(collection))
        {
            return null;
        }

        ITypeSymbol? entity = null;
        if (attribute.ConstructorArguments.Length > 1)
        {
            entity = attribute.ConstructorArguments[1].Value as ITypeSymbol;
        }

        entity ??= InferEntity(iface);
        if (entity is null)
        {
            return null;
        }

        var implName = ImplementationName(iface.Name);
        var ns = iface.ContainingNamespace.IsGlobalNamespace ? null : iface.ContainingNamespace.ToDisplayString();
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using Plugin.Maui.LocalStore;");
        if (ns is not null)
        {
            builder.AppendLine();
            builder.Append("namespace ").Append(ns).AppendLine(";");
        }

        builder.AppendLine();
        builder.Append("public sealed class ").Append(implName).Append(" : ").Append(iface.ToDisplayString()).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    readonly ILocalStore _store;");
        builder.Append("    readonly IStoreCollection<").Append(entity.ToDisplayString()).AppendLine("> _collection;");
        builder.AppendLine();
        builder.Append("    public ").Append(implName).AppendLine("(ILocalStore store)");
        builder.AppendLine("    {");
        builder.AppendLine("        _store = store ?? throw new System.ArgumentNullException(nameof(store));");
        builder.Append("        _collection = store.GetCollection<").Append(entity.ToDisplayString()).Append(">(\"")
            .Append(collection).AppendLine("\");");
        builder.AppendLine("    }");

        foreach (var method in iface.GetMembers().OfType<IMethodSymbol>().Where(m => m.MethodKind == MethodKind.Ordinary))
        {
            builder.AppendLine();
            WriteMethod(builder, method, entity);
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.Append("file static class ").Append(implName).AppendLine("Registration");
        builder.AppendLine("{");
        builder.AppendLine("    [ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.Append("        => StoreDao.Register<").Append(iface.ToDisplayString()).Append(">(store => new ")
            .Append(implName).AppendLine("(store));");
        builder.AppendLine("}");

        var hint = (ns is null ? implName : ns.Replace('.', '_') + "_" + implName) + ".g.cs";
        return new DaoModel(hint, builder.ToString());
    }

    static void WriteMethod(StringBuilder builder, IMethodSymbol method, ITypeSymbol entity)
    {
        var raw = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == RawAttribute);
        builder.Append("    public ");
        builder.Append(method.ReturnType.ToDisplayString());
        builder.Append(' ');
        builder.Append(method.Name);
        builder.Append('(');
        builder.Append(string.Join(", ", method.Parameters.Select(FormatParameter)));
        builder.AppendLine(")");
        builder.AppendLine("    {");

        if (raw is not null)
        {
            WriteRaw(builder, method, entity, raw);
        }
        else
        {
            WriteMapped(builder, method);
        }

        builder.AppendLine("    }");
    }

    static void WriteMapped(StringBuilder builder, IMethodSymbol method)
    {
        var name = StripAsync(method.Name);
        var ct = method.Parameters.LastOrDefault(p => p.Type.ToDisplayString() == "System.Threading.CancellationToken");
        var ctArg = ct is null ? "default" : ct.Name;
        var args = method.Parameters.Where(p => p.Type.ToDisplayString() != "System.Threading.CancellationToken").ToArray();

        string? call = name.ToLowerInvariant() switch
        {
            "insert" when args.Length == 1 =>
                $"_collection.InsertAsync({args[0].Name}, {ctArg})",
            "insertmany" when args.Length == 1 =>
                $"_collection.InsertManyAsync({args[0].Name}, {ctArg})",
            "findbyid" when args.Length == 1 =>
                $"_collection.FindByIdAsync({args[0].Name}, {ctArg})",
            "replace" when args.Length == 1 =>
                $"_collection.ReplaceAsync({args[0].Name}, {ctArg})",
            "deletebyid" or "delete" when args.Length == 1 =>
                $"_collection.DeleteByIdAsync({args[0].Name}, {ctArg})",
            "find" =>
                $"_collection.FindAsync({ArgOrDefault(args, 0, "null")}, {ArgOrDefault(args, 1, "null")}, {ctArg})",
            "ensureindex" when args.Length >= 1 =>
                $"_collection.EnsureIndexAsync({args[0].Name})",
            "query" when args.Length >= 1 =>
                $"_store.QueryAsync<{GenericArgument(method.ReturnType)}>({args[0].Name}, {ArgOrDefault(args, 1, "null")}, {ctArg})",
            _ => null
        };

        if (call is null)
        {
            builder.Append("        throw new LocalStoreException(\"DAO method ")
                .Append(method.Name)
                .AppendLine(" is not a collection method and has no [StoreRaw].\");");
            return;
        }

        if (IsAsyncVoid(method))
        {
            builder.Append("        return ").Append(call).AppendLine(";");
        }
        else
        {
            builder.Append("        return ").Append(call).AppendLine(";");
        }
    }

    static void WriteRaw(StringBuilder builder, IMethodSymbol method, ITypeSymbol entity, AttributeData raw)
    {
        var command = GetString(raw, "Command") ?? (raw.ConstructorArguments.Length == 1
            ? raw.ConstructorArguments[0].Value as string
            : null);
        var sql = GetString(raw, "Sql") ?? command;
        var nql = GetString(raw, "Nql") ?? command;
        var ct = method.Parameters.LastOrDefault(p => p.Type.ToDisplayString() == "System.Threading.CancellationToken");
        var ctArg = ct is null ? "default" : ct.Name;
        var values = method.Parameters
            .Where(p => p.Type.ToDisplayString() != "System.Threading.CancellationToken")
            .ToArray();
        var entityName = entity.ToDisplayString();

        builder.AppendLine("        var language = _store.QueryLanguage;");
        builder.Append("        if (language == StoreQueryLanguage.Sql && ");
        builder.Append(sql is null ? "false" : "true").AppendLine(")");
        builder.AppendLine("        {");
        if (sql is not null)
        {
            var (text, args) = ToSql(sql, values);
            builder.Append("            return _store.QueryAsync<").Append(entityName).Append(">(\"")
                .Append(Escape(text)).Append("\", ");
            builder.Append(args).Append(", ").Append(ctArg).AppendLine(");");
        }
        else
        {
            builder.AppendLine("            throw new LocalStoreException(\"This DAO method has no SQL text.\");");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append("        if (language == StoreQueryLanguage.Nql && ");
        builder.Append(nql is not null ? "true" : "false").AppendLine(")");
        builder.AppendLine("        {");
        if (nql is not null)
        {
            builder.Append("            var nql = StoreCommand.Bind(\"").Append(Escape(nql))
                .AppendLine("\", new Dictionary<string, object?>");
            builder.AppendLine("            {");
            foreach (var parameter in values)
            {
                builder.Append("                [\"").Append(parameter.Name).Append("\"] = ")
                    .Append(parameter.Name).AppendLine(",");
            }

            builder.AppendLine("            }, StoreQueryLanguage.Nql);");
            builder.Append("            return _store.QueryAsync<").Append(entityName).Append(">(nql, null, ")
                .Append(ctArg).AppendLine(");");
        }
        else
        {
            builder.AppendLine("            throw new LocalStoreException(\"This DAO method has no NQL text.\");");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        throw new LocalStoreException($\"{_store.Backend} has no SQL or NQL.\");");
    }

    static (string Sql, string ArgsLiteral) ToSql(string template, IParameterSymbol[] values)
    {
        var order = new List<string>();
        var sql = new StringBuilder();
        for (var i = 0; i < template.Length; i++)
        {
            if (template[i] == '{')
            {
                var end = template.IndexOf('}', i);
                if (end > i)
                {
                    var key = template.Substring(i + 1, end - i - 1);
                    if (values.Any(v => v.Name == key) || int.TryParse(key, out _))
                    {
                        order.Add(int.TryParse(key, out var index) && index >= 0 && index < values.Length
                            ? values[index].Name
                            : key);
                        sql.Append('?');
                        i = end;
                        continue;
                    }
                }
            }

            sql.Append(template[i]);
        }

        var args = order.Count == 0
            ? "null"
            : "new object?[] { " + string.Join(", ", order) + " }";
        return (sql.ToString(), args);
    }

    static string? GetString(AttributeData data, string name)
    {
        foreach (var pair in data.NamedArguments)
        {
            if (pair.Key == name)
            {
                return pair.Value.Value as string;
            }
        }

        return null;
    }

    static ITypeSymbol? InferEntity(INamedTypeSymbol iface)
    {
        foreach (var method in iface.GetMembers().OfType<IMethodSymbol>())
        {
            var name = StripAsync(method.Name).ToLowerInvariant();
            if (name is "insert" or "replace")
            {
                var first = method.Parameters.FirstOrDefault();
                if (first?.Type is { TypeKind: TypeKind.Class or TypeKind.Struct })
                {
                    return first.Type;
                }
            }

            if (name == "findbyid")
            {
                return Unwrap(method.ReturnType);
            }
        }

        return null;
    }

    static ITypeSymbol? Unwrap(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            var def = named.ConstructedFrom.ToDisplayString();
            if (def is "System.Threading.Tasks.Task<TResult>" or "System.Threading.Tasks.ValueTask<TResult>")
            {
                return Unwrap(named.TypeArguments[0]);
            }
        }

        return type.NullableAnnotation == NullableAnnotation.Annotated && type is INamedTypeSymbol n
            ? n.OriginalDefinition.SpecialType == SpecialType.None ? n : type
            : type;
    }

    static string FormatParameter(IParameterSymbol parameter)
    {
        var text = new StringBuilder();
        if (parameter.IsParams)
        {
            text.Append("params ");
        }

        text.Append(parameter.Type.ToDisplayString());
        text.Append(' ');
        text.Append(parameter.Name);
        if (parameter.HasExplicitDefaultValue)
        {
            text.Append(" = default");
        }

        return text.ToString();
    }

    static string ArgOrDefault(IParameterSymbol[] args, int index, string fallback) =>
        index < args.Length ? args[index].Name : fallback;

    static string GenericArgument(ITypeSymbol returnType)
    {
        if (returnType is INamedTypeSymbol named && named.IsGenericType && named.TypeArguments.Length > 0)
        {
            var inner = named.TypeArguments[0];
            if (inner is INamedTypeSymbol list && list.IsGenericType && list.TypeArguments.Length == 1)
            {
                return list.TypeArguments[0].ToDisplayString();
            }

            return inner.ToDisplayString();
        }

        return returnType.ToDisplayString();
    }

    static bool IsAsyncVoid(IMethodSymbol method) =>
        method.ReturnType.ToDisplayString() is "System.Threading.Tasks.Task" or "System.Threading.Tasks.ValueTask";

    static string StripAsync(string name) =>
        name.EndsWith("Async", StringComparison.Ordinal) ? name.Substring(0, name.Length - 5) : name;

    static string ImplementationName(string interfaceName) =>
        interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName + "Implementation";

    static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");

    sealed class DaoModel
    {
        public DaoModel(string hintName, string source)
        {
            HintName = hintName;
            Source = source;
        }

        public string HintName { get; }

        public string Source { get; }
    }
}
